import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Footer from '@/components/footer'
import Navbar from "@/components/navbar";
import LocationSection from "@/components/map";
import { toast } from "react-toastify"; // ✅ Import 
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <ToastContainer position="top-right" autoClose={3000} />
        <main className="pt-24">{children}</main> 
        {/* <LocationSection /> */}
        <Footer />
      </body>
    </html>
  );
}
